### ISSUE TITLE
Adapt colorscheme  for pydata-sphinx-theme>=0.9

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/mpl-sphinx-theme#32]
pydata-sphinx-theme 0.9 has been released recently and it has changed it's default styling, which breaks our custom styling, in particular the heading colors.

We've now pinned to pydata-sphinx-theme>=0.9, so we need to adapt our customization to this.

Please also check whether there are any other obivous changes in the new theme version.

**Comment by jklymak** [comment]
I'm not sure we want to use 0.9 yet, to be honest.  I am not sure how to wrap it with this theme, and it has a bunch of css-theme related stuff that is all marked beta and subject to change.  https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/. Maybe @choldgraf has some suggestions for how we should proceed.

**Comment by jklymak** [comment]
OK, Maybe not as bad as I thought.  I'd misunderstood how the inheritance works...

**Comment by timhoffm** [comment]
Closed by #33.
