### ISSUE TITLE
Theme is not testable

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/mpl-sphinx-theme#35]
The current state of the theme cannot be tested.

This is in particular troublesome as pydata sphinx theme has introduced some changes, which we try to adapt to here, but that change is not yet reflected in the matplotlib devdocs.

Do one or more of

- [ ] Add a simple test site to mpl-sphinx-theme, that is automatically build with every PR. The site should also be deployed somewhere similar to devdocs.
- [ ] Make the other matplotlib dev builds take mpl-sphinx-theme git HEAD instead of the released version.
- [ ] As a stop-gap do a release of the current state.

**Comment by timhoffm** [comment]
Thanks for the hint. The test site is quite minimalistic, so we can't see many aspects of the theme
https://output.circle-artifacts.com/output/job/b750813b-26d4-4d89-9588-0d35f665e9c4/artifacts/0/docs/_build/html/index.html

Also it's a bit cumbersome to access (open the last PR and go to its CI section).

**Comment by jklymak** [comment]
I think the test site makes use of all the features I know about, but we can add more. I don't understand the concern with drilling down to CI - that is how all our tests work.  Changing matplotlib dev builds to use head is probably a good idea.

**Comment by jklymak** [comment]
@QuLogic or @tacaswell can either of you enable GH pages from main?  

For Matplotlib, I think it would make sense to build off master for the dev docs.  

For releasing, probably should do just before the docs are released, and maybe make the version number the same?

**Comment by QuLogic** [comment]
Enabling GH Pages is not necessary as everything on the site is routed through the DO server. I can add this to the server config, but it won't do anything without the branch with built docs.

**Comment by QuLogic** [comment]
The `main` branch now gets posted at https://matplotlib.org/mpl-sphinx-theme/

**Comment by timhoffm** [comment]
Main is good enough for now. Thanks.
