### ISSUE TITLE
Tag an rc

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/mpl-sphinx-theme#41]
Please tag & upload a 3.6.0 release candidate to PyPI, so I can start building the Matplotlib rc docs against it.

**Comment by jklymak** [comment]
OK at https://pypi.org/project/mpl-sphinx-theme/3.6.0.dev0/

**Comment by jklymak** [comment]
Is this closed for you @QuLogic?

**Comment by jklymak** [comment]
https://pypi.org/project/mpl-sphinx-theme/ now has a 3.6 release.

**Comment by QuLogic** [comment]
Thanks! Can you also upload a wheel? I realized we're only Python here, but because @tacaswell added `--prefer-binary`, the 3.6 doesn't install by default because 3.5 is the last one to have wheels.

**Comment by jklymak** [comment]
OK,think I've done it correctly:

https://pypi.org/project/mpl-sphinx-theme/3.6.0/#files

I actually don't know the difference.  Should I only upload one of these, or both each time.

**Comment by QuLogic** [comment]
Wheels are now the official PyPI distribution format, which can avoid requiring special package builders and such. But the sdist is also useful for other distributors. So in short, we should upload both.

**Comment by QuLogic** [comment]
Ran a test build and I think everything we changed is where it's expected.
