### ISSUE TITLE
Remove the search field from index?

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/mpl-sphinx-theme#42]
The new pydata-sphinx-theme uses a search button and an input overlay

On https://matplotlib.org/devdocs/index.html we still have the search field in the side bar. Clicking the search button in the titlebar now focusses the search field in the sidebar, which is quite surprising.

**Comment by QuLogic** [comment]
This was fixed by https://github.com/matplotlib/matplotlib/pull/23833, I think.
