### ISSUE TITLE
Social icons etc... hover behaviour inconsistent.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/mpl-sphinx-theme#45]
The social icons have no hover color.  The search has a blue hover color, and the theme switcher has extra shading.  We should probably make more coherent.

**Comment by timhoffm** [comment]
#46 uses the regular link hover color (orange), which might be a bit strong but OTOH is consistent with the link character.

I think search and theme switcher can and maybe should have a different hover behavior. Of course, among them, they should be consistent. But that should be addressed at the pydata-sphinx-theme level. They are currently inconsistent there:  https://pydata-sphinx-theme.readthedocs.io/en/stable/.

**Comment by jklymak** [comment]
Closed by #46
