### ISSUE TITLE
Release other pages with the new theme

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/mpl-sphinx-theme#49]
Not sure where this belongs. All pages should be updated using the recent 3.6.0 release of this theme.

This is at least:
- https://matplotlib.org/
- https://matplotlib.org/mpl-third-party/

**Comment by QuLogic** [comment]
- https://github.com/matplotlib/mpl-brochure-site/pull/61
- https://github.com/matplotlib/mpl-gui/pull/10
- https://github.com/matplotlib/mpl-third-party/pull/134
- https://github.com/matplotlib/governance/pull/32

I did not fix cheatsheets, as that has a more complicated update process, and I guess needs to be fully audited to work with 3.6.

**Comment by timhoffm** [comment]
All done.
