### ISSUE TITLE
ENH: better if `icon_links` could have a set default

### ISSUE THREAD

**Issue by jklymak** [matplotlib/mpl-sphinx-theme#7]
Right now the way this is set up `icon_links` must be manually specified in `docs/conf.py` in each project  https://github.com/matplotlib/mpl-sphinx-theme/blob/b10c4717840b29064718c26174526b0621a67cf2/docs/conf.py#L38-L59  I assume this could be made the default somehow in `theme.conf`, but I could not make it work.

Similarly, 

```
html_logo = "_static/logo2.svg"
html_favicon = "_static/favicon.ico"
```

are going to be the same and it would be nice if this were part of the theme.

@choldgraf I know you are probably busy, but if you have any suggestions for how to make this happen, happy to try, or to accept a PR...

**Comment by choldgraf** [comment]
that seems like a reasonable fix - another thing you could try if it simplifies things is to define a little Sphinx callback function that configures those links at build time. Something like:

```python
def update_topbar_links(app, env):
  theme_options = app.config.html_theme_options
  if not theme_options.get("icon_links"):
    theme_options["icon_links"] = ...yourlinkshere...

def setup(app):
  app.connect("env-updated", update_topbar_links)
```
