### ISSUE TITLE
Gitter link needs to be fixed

### ISSUE THREAD

**Issue by jklymak** [matplotlib/mpl-sphinx-theme#73]
### Documentation Link

https://matplotlib.org/stable/index.html

### Problem

The link to gitter is broken in the top banner, which I guess is outdated.

### Suggested improvement

This link should be good: https://gitter.im/matplotlib/matplotlib

_Originally posted by @stevezhang1999 in https://github.com/matplotlib/matplotlib/issues/26391_

**Comment by QuLogic** [comment]
This was already fixed by #59; I must have not updated the venv when building the docs.

**Comment by QuLogic** [comment]
Actually, we seem to have some kind of inconsistency on the `v3.7.x` branch. It requires `mpl-sphinx-theme~=3.7.0` and `pydata-sphinx-theme~=0.12.0`. However, `mpl-sphinx-theme` 3.7.1 (which has this fix) requires `pydata-sphinx-theme~=0.13.0`, so it can't be installed.

**Comment by QuLogic** [comment]
I pushed a direct fix to the docs repo. I'll just have to remember this for 3.7.3 if it happens. 3.8 should be fine since it's been updated to `pydata-sphinx-theme~=0.13.0`.
